### PR TITLE
Always use the latest version of geerlingguy.docker dependency

### PR DESCRIPTION
**Pull request by Normo**

### CODE REVIEW

**Comment by Normo** [comment]
@tobiashuste Do you think we should specify a specific version here?

**Comment by tobiashuste** [comment]
> @tobiashuste Do you think we should specify a specific version here?

Do I understand that your sugggestion is to remove the specific version requirement specification?

**Comment by tobiashuste** [comment]
> @tobiashuste Do you think we should specify a specific version here?

Do I understand that your sugggestion is to remove the specific version requirement specification?

**Review by tobiashuste — APPROVED** [review]
Thanks :shipit:

**Pull request merged**
