### PR TITLE
Release version 0.6.0

### LINKED ISSUE #23: Release version 0.6.0

### PR DESCRIPTION
**Pull request by tobiashuste**
Closes #23

### CODE REVIEW

**Comment by tobiashuste** [comment]
@Normo I noticed that I need to fix #31 before merging this one.

**Review by Normo — APPROVED** [review]
LGTM :+1:

**Review by Normo — CHANGES_REQUESTED** [review]
Please re-generate the changelog ;)

**Comment by tobiashuste** [comment]
@Normo The changelog is now up-to-date including the correct date.

**Comment by tobiashuste** [comment]
@Normo Please note d953cf9f58712e4b4c6916f28a063dae5ce72aa5. This was required since `reuse lint` complains if the copyright notice is given too deep in the file.
This happened for the CHANGELOG here. Compare with https://github.com/hifis-net/ansible-role-gitlab-runner/runs/6930651275?check_suite_focus=true#step:4:29.

**Review by Normo — APPROVED** [review]
LGTM :+1:

**Pull request merged**
